version: '3.1'

services:

  db:
    image: mysql:5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: "filedb"
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  backend:
    restart: unless-stopped
    depends_on:
      - db
    build: file-server
    ports:
      - 8082:9090
    expose:
      - "9090"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/filedb?autoReconnect=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root"
      }'
